#!/bin/sh

commit_msg_file=$1

# 从提交信息文件中读取提交信息内容
commit_msg=$(cat $commit_msg_file)

# 定义提交信息的正则表达式模式，用于验证格式
pattern="[A-Z]{2,}-[0-9]{1,}: .+"

# 使用正则表达式进行格式验证
if ! echo "$commit_msg" | grep -qE "$pattern"; then
    echo "提交信息格式错误，请按照规范格式提交。"
    exit 1
fi
# #!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# npx --no-install commitlint --edit "$1"